name: Deploy to Server

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-14.10.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.10.0"

      - name: Install Dependencies
        run: npm install

- name: Deploy via SSH
  run: |
    echo "$SSH_PRIVATE_KEY" > ssh_key
    chmod 600 ssh_key
    scp -i ssh_key -o StrictHostKeyChecking=no -r ./apps/TanProServer_2 hobapro@16.171.169.226:/path/to/destination/myapp
  env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}