name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          host: 16.171.169.226
          username: hobapro
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /apps/TanProServer_2
            git pull
            npm install
            pm2 restart index.js
