name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploying Commands
        run: |
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          ssh -i "$SSH_KEY" -p "$SSH_PORT" "$SSH_USER"@"$SSH_HOST" "pm2 delete all; cd /apps/TanProServer_2; git pull; npm install; pm2 start npm -- start"
        env:
          NAME: Mohab
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}